### ISSUE TITLE
How to export deck.json

### ISSUE THREAD

**Issue by dreamflasher** [JouzaLoL/anki-sort-by-frequency#1]
Anki decks are in apkg format, how do I convert this to .json as required by your script?

**Comment by vacekj** [comment]
Hi, sorry for the delay. You can use an Anki addon for converting decks to json, [here is a link.](https://ankiweb.net/shared/info/1589071665)

I'll close this issue for now and edit the README with a link to the addon.. If you have any additional questions please don't hesitate to ask.
