### ISSUE TITLE
How do I use the frequency list to actually sort my anki deck?

### ISSUE THREAD

**Issue by dreamflasher** [JouzaLoL/anki-sort-by-frequency#2]
Thank you for your script, I now have the frequency list for my deck in the output folder. How do I sort the deck by it?

**Comment by vacekj** [comment]
Hi, you can import the output.txt file into Anki, choosing tab separated in Anki import dialog. It will then create a deck with Basic note type, where front will be the frequency, and back will be the word. You can the sort it by viewing it in Anki Card Browser and clicking the frequency field to sort it descending. Higher number means higher frequency.

**Comment by dreamflasher** [comment]
Okay, that's not what I intended to do. In your reddit post you wrote that you wanted to sort the cards by frequency and then let Anki ask them by frequency (in order to focus on the most important ones first). Do you also have a solution for that? Thanks!
